### ISSUE TITLE
undo and redo are not working at all after refreshing a file

### ISSUE THREAD

**Issue by badr131** [Supernova-Studio/public-issue-tracker#140] opened 2019-08-19 13:50 UTC
### Issue
> 	undo and redo are not working at all after refreshing a file

### Context
> 
- open Supernova 7.2
- choose my main doc
- edit a screen, deleting something
- Undo (undo working)
- Refresh that screen by reimporting just it from Sketch
- Try to remove something on the screen - item vanishes
- Undo - you can't
### Expected result
> 	there should be no problem after refreshing the template

**Comment by jan-supernova** [comment] 2019-08-21 13:34
Hey badr131,
Thank you very much for your report. We have been able to simulate the issue in the latest version of Supernova Studio V7.2. We are working hard on fixing this issue as soon as possible. We will let you know when the issue is resolved. Thank you again for your report!

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-09-09 10:18
Hey badr131,
We would like to inform you that the issue with undo and redo operations not being available after refreshing a file has been resolved in the latest version of the Supernova Studio V7.4. Thank you again for your report!

Have a wonderful day!
Jan, Supernova Team

**Closed by jan-supernova** 2019-09-09 10:18 UTC
