### ISSUE TITLE
Simulators setting not found

### ISSUE THREAD

**Issue by pinotao** [Supernova-Studio/public-issue-tracker#27] opened 2017-08-03 15:55 UTC
### Issue
your documents said : 
> 	Simulators ： To run your application in the simulator, click on the "Simulator" option in the top toolbar, and pick either iOS or Android platform.

but  I can't find the toolbar 。

![image](https://user-images.githubusercontent.com/4969884/28930722-70cbb614-78a6-11e7-8103-aa03ab7f7596.png)

**Comment by JiriTrecak** [comment] 2017-08-03 16:00
Hey @pinotao, this is true, you can see the icon of the simulator on the other side of the bar -
 on the right (simulator) and you can also see that it is disabled. We are currently polishing this feature and it will be re-enabled very soon. Documentation is prepared for this option in advance... Sorry for the inconvenience and thank you for reading so thoroughly!

**Comment by JiriTrecak** [comment] 2017-08-03 16:01
Duplicate of #3

**Closed by JiriTrecak** 2017-08-03 16:01 UTC
Labels: Core Engine, Enhancement
