### ISSUE TITLE
Flutter code export issue. 

### ISSUE THREAD

**Issue by mvgeek** [Supernova-Studio/public-issue-tracker#127] opened 2019-07-16 10:10 UTC
### Issue
> 	Flutter code export isn't exporting image constraints and borders.

### Context
> 	I've designed a screen with a couple of elements:
        1- Background with a svgs.
        2- Logo (image on the top of the screen)
        3- Welcome text.
        4- Two buttons. (one is a solid btn, the second one is secondary with border)

### Expected result
> 	​I expected the background SVG's to be where it was supposed to be, in the exported code the constraints weren't there.
The logo position constraints weren't there.
The secondary button didn't have a border either.
all of these looked good on supernova canvas. The only problem is with the exported code. SO I checked it and I couldn't find the code I expected. the above-mentioned properties were missing.

### Current result
> 	So what I'm trying to do is manually fix the exported code once I get it.

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	I have sent screenshots along with the exported codes and my sketch file to support@supernova.io
--

**Comment by jan-supernova** [comment] 2019-07-18 09:33
Hey mvgeek,
 Thank you for your detailed report and for the files you have sent to us. We have been able to successfully reproduce the issue using the latest version of Supernova. We will try to fix the issue as soon as possible. I will let you know when the issue is resolved. Thank you again for your report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-23 11:35
Hey mvgeek,
We would like to inform you that your reported issue has been fixed in the latest version of the Supernova Studio.

Have a wonderful day!
Jan, Supernova Team

**Closed** 2019-08-23 11:35 UTC
