### ISSUE TITLE
Supernova - Import and export not working after upgrading from Free version Export and Import screens doesnt show a scroll and getting struck

### ISSUE THREAD

**Issue by HMaliniV** [Supernova-Studio/public-issue-tracker#113] opened 2019-05-24 17:08 UTC
### Issue
> 	[Provide general introduction to the issue]

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by jan-supernova** [comment] 2019-07-09 09:05
Hey HMaliniV,  
We have not been able to successfully reproduce the issue with the information provided. Is it possible to provide us with more information if the issue is still occurring? Thank you very much for the answer. 

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-11-04 11:42
Hey HMaliniV,
Since the issue hasn’t been clarified and we have not been able to simulate it in the newest version of the Supernova Studio V7.9, we are closing this ticket. If the issue still persists in the future, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!
Jan, Supernova Team

**Closed by jan-supernova** 2019-11-04 11:42 UTC
