### ISSUE TITLE
After Refreshing - Preview Image on Navigation View is Old

### ISSUE THREAD

**Issue by bigmountainstudio** [Supernova-Studio/public-issue-tracker#90] opened 2019-03-11 02:40 UTC
### Issue
> 	If I change a Sketch image and Refresh, I notice the thumbnail in the navigation window is still the old image.

### Context
> 	When you first import and go to the navigation window, you see a thumbnail of what the artboard/screen looks like. If you go back into Sketch and change some obvious colors and Refresh, you'll notice the thumbnail in the navigation window still shows the old one. At some point, it does get updated.

### Expected result
> 	Thumbnails should refresh to the new screen after a Refresh is done.

### Current result
> 	Shows the previous screen before refresh.

### Possible fix
> 	Run a refresh to generate new thumbnails after a Refresh is done.
### Screenshots
> 	
<img width="500" alt="1-Starting Color" src="https://user-images.githubusercontent.com/24855856/54097199-95ccb900-4374-11e9-9726-1730c689c802.png">
<img width="500" alt="2-Change Color" src="https://user-images.githubusercontent.com/24855856/54097200-95ccb900-4374-11e9-810f-a3a86736a4a3.png">
<img width="500" alt="3-Refresh" src="https://user-images.githubusercontent.com/24855856/54097201-95ccb900-4374-11e9-9eaa-f27db2cdb859.png">
<img width="500" alt="4-Nav Image not refreshed" src="https://user-images.githubusercontent.com/24855856/54097202-95ccb900-4374-11e9-8622-c7a4c2fe5905.png">

**Comment by jan-supernova** [comment] 2019-09-02 08:57
Hey bigmountainstudio,
Thank you for your report! We have been able to successfully simulate the issue in the latest version of the Supernova Studio V7.3. We are working hard on fixing the issue as soon as possible. We will let you know when the issue is resolved. Thank you again for you report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2020-02-10 10:42
Hey bigmountainstudio,
We are happy to let you know that your issue had been resolved in the newest version of the Supernova Studio V8.3. Thank you again for you report.

Have a wonderful day!
Jan, Supernova Team

**Closed by jan-supernova** 2020-02-10 10:42 UTC
