### ISSUE TITLE
Imported screen does not obey the Symbol Overrides from Layer Styles

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#128] opened 2019-07-30 14:07 UTC
### Issue
When importing a screen which has symbols that have Layer Styles, the _original_ styling of the symbol is used, not the styles applied via Layer Style overrides.

#### Observed in Supernova Version
7.0 pre-release

### Expected result
Symbols should use the Layer Styles specified by overrides, _not_ the Layer Styles which are on the _original_ symbols

### Current result
Symbols use the Layer Styles applied to the Symbol

### Possible fix
n/a

### Screenshots
Screenshot shows:

- Original WHITE fill Layer Style on the Symbol in Sketch
- BLUE fill Layer Style applied by a Symbol override in Sketch
- Original WHITE fill Layer Style is used when the symbol is imported into Supernova Studio, instead of the BLUE Layer Style

![Forget_Me_Not_sketch_and_actionSheetAnimation_sketch](https://user-images.githubusercontent.com/12557929/62136227-9510d100-b2db-11e9-882d-92b4d873fe2c.png)

**Comment by jan-supernova** [comment] 2019-07-30 14:26
Hi Steve!
Thank you for your very detailed report! We have been able to successfully reproduce the issue in Supernova V7.0. We will try to fix the issue as soon as possible. I will let you know when the issue is resolved. Thank you again for your report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-14 08:50
Hey Steve!
We would like to inform you that this issue had been fixed in the newest version of the Supernova Studio. Imported screens in Supernova Studio V7 now correctly obey symbol overrides.

Have a wonderful day!
Jan, Supernova Team

**Closed** 2019-08-14 08:50 UTC
