### ISSUE TITLE
Select single screen for export requires control-click in 6.10

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#125] opened 2019-07-10 14:22 UTC
### Issue
Wanting to export a single screen, in Files mode, is non-standard in requiring immediate use of ctrl-click.

### Context
- choose Export
- switch to Files mode
- press Deselect All
- attempt to click on a window to export

### Expected result
window clicked on would be highlighted

### Current result
no reaction to the click.

Eventually tried different moderator keys and found that ctrl-click worked. 

Normally, when doing ad-hoc selection within a spatial collection, such as a grid, the **first** selection is made with an unqualified click then shift-click used to establish a rectangular selection or ctrl-click to toggle the selection status of individual items.

**Comment by jan-supernova** [comment] 2019-07-11 07:10
Hey AndyDentFree,
     Thank you for your very detailed report. We have been able to successfully reproduce the issue you have reported to us. We will try to fix it as soon as possible. I will you let you know when the issue is resolved. 

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-23 13:35
Hey AndyDentFree,
We are happy to inform you that your reported issue has been fixed in the latest version of Supernova Studio V7.2.

Have a wonderful day!
Jan, Supernova Team

**Closed** 2019-08-23 13:35 UTC
