### ISSUE TITLE
[react-native] Incorrect typeface weight & wrapping of text

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#108] opened 2019-04-10 07:31 UTC
### Environment
```react-native-cli: 2.0.1
xcode-select version 2354
Xcode 10.1, Build version 10B61
macOS 10.14.3
node v8.9.1
cocoapods 1.6.1
supernova 6.6

### Issue
The weight & formatting of text is still incorrect when exported to react  

### Context
Export a simple 1-screen file from Supernova Studio to react and deploy to the ios simulator with `react-native run-ios`

### Expected result
Typeface & line wrap should match the imported Sketch file

### Current result
There are two fonts used in my sample screen; Font Awesome Pro 5 & Roboto Medium.  Roboto isn't being rendered as a Medium weight when exported to React and lines are wrapping when they shouldn't be.  It's  also possible that the exported text in react is also slightly larger than it should be - hard to tell

### Possible fix
unknown

### Screenshots

![supernova_v66](https://user-images.githubusercontent.com/12557929/55859954-0f6de780-5b6b-11e9-8c37-03d778fd5e7a.png)

**Comment by jan-supernova** [comment] 2019-07-01 13:07
Dear steveharman,
     We have been unable to reproduce your reported issue on the newest version of Supernova Studio (V6.10 build 5940). Is the issue still occurring in the newest version of Supernova Studio? If so, would it be possible to provide us with the Supernova project file? Thank you for the answer.

Kind Regards,
     Jan Poisl

**Comment by jan-supernova** [comment] 2019-11-04 11:48
Hey steveharman,
Since the issue hasn’t been clarified for quite some time, we are closing this ticket. If you encounter this issue again or it still persists, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!
Jan, Supernova Team

**Closed** 2019-11-04 11:48 UTC
