### ISSUE TITLE
Animations play in wrong place after editing properties (v6.2)

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#99] opened 2019-03-18 19:25 UTC
### Issue
When you have an animation and go edit any property in the animation editor, then animation then calculates positions wrongly.

### Context
I have an animation of several items moving into place, original [here on github](https://github.com/AndyDentFree/animashing/tree/master/AnimatingComponentsIntoView) which animates X and Y positions.

I found if I use any of the animation editing panels, eg: adjust timing curve, property values or timeline, that the animation then plays incorrectly.

Going to Preview and then back to Edit mode corrects this.

### Expected result
Animation should play correctly after editing properties.

### Current result
Any edit to animation causes playback to be in the wrong location.

### Screenshots
Zipped movie attached:

[Supernova6.2 animation position bug.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/2979900/Supernova6.2.animation.position.bug.zip)

**Comment by jan-supernova** [comment] 2019-07-03 08:53
Dear AndyDentFree,
     Thank you very much for very detailed description of the issue. We have been able to successfully reproduce the issue even in the newest V6.10 version, so the issue is still present. Our developers will look at the issue and we will notify you when the issue is fixed. Have a wonderful day!

Kind Regards,
     Jan Poisl

**Comment by jan-supernova** [comment] 2019-08-29 07:34
Dear AndyDentFree,
We are happy to inform you that this issue had been fixed in the latest version of Supernova Studio V7.3. Thank you again for your report!

Have a wonderful day!  
Jan, Supernova Team

**Closed by jan-supernova** 2019-08-29 07:34 UTC
