### ISSUE TITLE
Editing animation duration causes application to crash

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#129] opened 2019-07-30 14:44 UTC
### Issue
Editing the duration of an animation can cause Supernova Studio to crash.

### Observed in Supernova version
7.0 pre-release
macOS 10.14.5

### Context
I have a trigger animation that applies a Translate Y operation to one of my layers.  Its initial duration of 0.05s is too short so I want to extend it out to a much longer 3s.  

I edit the duration value from 0.05s to 3s and press return.

### Expected result
Should apply a longer duration to my animation (and not crash!)

### Current result
Supernova Studio crashes.

### Possible fix
n/a

### Screenshots
mp4 video attached as a .zip

[supernovaCrash.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3447315/supernovaCrash.mp4.zip)

![Window_and_Banners_and_Alerts_and_Problem_Report_for_Supernova_Studio_and_Exports](https://user-images.githubusercontent.com/12557929/62139229-df488100-b2e0-11e9-8ec1-d9c752fb23c9.png)

**Comment by jan-supernova** [comment] 2019-07-31 14:30
Hi Steve!  
Thank you for your report! We have been able to successfully reproduce your reported issue in Supernova V7.0. As a temporary workaround, you can add the second keyframe, which will make Supernova not crash anymore when changing the duration of the animation. We will try to fix the issue as soon as possible and I will let you know when the issue is resolved. Thank you again for your report!

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-14 09:12
Hey Steve!
Your reported issue had been fixed in the newest version of Supernova Studio. There had been few changes made in the animation editor and your reported issue is no longer present in V7.

Have a wonderful day!
Jan, Supernova Team

**Closed** 2019-08-14 09:12 UTC
