### ISSUE TITLE
WebView + Local HTML Assets Loading

### ISSUE THREAD

**Issue by vishwaprabhu** [Supernova-Studio/public-issue-tracker#161] opened 2019-10-19 11:57 UTC
### Issue
> 	[ UI Webview only works on preview not on Simulator or Actual Device ( IOS ).  WK Webview + Local Html Require on **Next Update**  ]

### Context
![Group@3x](https://user-images.githubusercontent.com/38086478/67144374-5ca5e100-f293-11e9-9ce6-9b82a301d198.png)

> 	​[Local Html file shall be loaded for alternate solution for webview OR if both are avail on next Update thats Awesome...!]

**Comment by jan-supernova** [comment] 2019-10-21 08:51
Hey vishwaprabhu,
Thank you for your report. We have been able to simulate the issue with the Web View component and we are currently working on fixing as quickly as possible - it will be fixed in the next update. We will let you know once the issue is resolved.

Have a wonderful day!  
Jan, Supernova Team

**Comment by vishwaprabhu** [comment] 2019-10-21 08:55
Ok Thanks Jan..

**Closed** 2019-10-25 09:03 UTC
