### ISSUE TITLE
V7 iOS animations not compiling due use of property rather than group

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#132] opened 2019-08-05 08:23 UTC
### Issue
Code in v7 added a bug in iOS Animations that result in exported code not compiling.

### Context
The line `animationProperty1.animations?.append(animationProperty1)` fails to compile

As seen in [this export](https://github.com/AndyDentFree/DDD19/blob/master/menuAnimationDemo/menuAnimation_iOSExport/menuAnimation/Classes/Controllers/DocTree/DocTreeViewController.swift#L120)

### Expected result
As happened in v6, animations are appended to `animationElement1.animations`

### Current result
Animations are wrongly appended to `animationProperty1.animations`

**Comment by jan-supernova** [comment] 2019-08-07 13:52
Hey Andy,
     Thank you for the report. We have been able to simulate the issue in Supernova V7.0 and we are working hard on fixing it as soon as possible. I will let you know when the issue is resolved. Thank you again for your report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-27 13:07
Hey AndyDentFree,
We are happy to inform you that your reported issue had been fixed in the latest version of Supernova Studio V7.3. Thank you again for your report!

Have a wonderful day!  
Jan, Supernova Team

**Closed by jan-supernova** 2019-08-27 13:07 UTC
