### ISSUE TITLE
Animation "scale" input fields do not show the values I enter into them?

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#130] opened 2019-08-01 16:16 UTC
### Issue
 Is this just my misunderstanding of the expected behavior, or a UI glitch?

### Observed in version
7.0 pre-release

### Context
In Animation I have a component which I apply a scale value to (case: X & Y scale of 0.5) and sure enough and the component itself shrinks to half its size.  

### Expected result
The X & Y fields I enter my values into should continue to display the values I keyed in?

### Current result
The X & Y input fields where I entered my "0.5" scale values to continue to show the value of "1".

### Possible fix
n/a

### Screenshots
Video attached as a .zip

[supernovaAnimation.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3457680/supernovaAnimation.mp4.zip)

**Comment by jan-supernova** [comment] 2019-08-13 12:35
Hey steveharman,
      We have checked your reported issue in the latest V7.0 version of Supernova Studio. This is UI glitch that happens when only one animation keyframe for the particular animation type exists. We will fix this issue as soon as possible. We will let you know when the issue is fixed. Thank you again for your report!

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment] 2019-08-27 09:43
Hey steveharman,
We are happy to inform you that your reported issue had been fixed in the latest version of Supernova Studio V7.3. Thank you again for your report!

Have a wonderful day!
Jan, Supernova Team

**Closed by jan-supernova** 2019-08-27 09:43 UTC
